name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  common:
    name: Common
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x", "20.x", "22.x"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test:run

  playwright:
    name: Playwright tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x", "20.x", "22.x"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build dependencies
        run: pnpm turbo build --filter=...@repo/playwright-example

      - name: Install Playwright Browsers
        working-directory: ./examples/playwright
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        working-directory: ./examples/playwright
        run: npx playwright test
